### ISSUE TITLE
SpecAdminList problem

### ISSUE THREAD

**Issue by Ziragog** [awesomeusername69420/miscellaneous-gmod-stuff#1]
Hi awesome.
at a certain point, an error appears.

[ERROR] RunString:88: invalid order function for sorting
  1. sort - [C]:-1
   2. unknown - RunString:88

Timer Failed! [@][@RunString (line 78)]

edit:
local function IsSpectating(spectator, ply) -- Checks if a spectator is spectating a specific player
	if not IsValid(spectator) or not IsValid(ply) then
		return false
	end
	
	if spectator:GetObserverMode() == OBS_MODE_NONE then
		return false
	end
	
	local specEnt = spectator:GetObserverTarget()
	
	if not IsValid(specEnt) then
		return false
	end
	
	return specEnt == LocalPlayer() or specEnt:GetParent() == LocalPlayer()
end

timer.Create("@", 0.3, 0, function()

	CACHE.Spectators = {}
	
	for _, v in ipairs(player.GetAll()) do
		if v:GetObserverMode() ~= OBS_MODE_NONE then
			CACHE.Spectators[#CACHE.Spectators + 1] = v
		end
	end
	
	table.sort(CACHE.Spectators, function(a) -- Show people spectating you at the top
		return IsSpectating(a, LocalPlayer())
	end)
end)

Gamemode (zombiesurvival)

**Comment by Ziragog** [comment]
symptoms:
 The numbers stop being updated.
all players are removed from the spec list on the next round. the digit is still stopped

**Comment by awesomeusername69420** [comment]
I haven't been able to reproduce this. What server were you on?
