### ISSUE TITLE
aimtri.lua not working

### ISSUE THREAD

**Issue by M-a-l-w-a-r-e1** [awesomeusername69420/miscellaneous-gmod-stuff#2]
shit dont fire and its the latest file 
server ip: 23.247.169.1:27015
unless it's swag tools fucking it up idk

**Comment by awesomeusername69420** [comment]
AimTri works fine on its own.
I tested it with Swag Tools loaded, it works fine.

I loaded AimTri first and it works fine, I loaded Swag Tools first and it also works fine.
There is something else at fault.
